{% set name = "e13tools" %}
{% set version = "0.9.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c6eab60825a644e4a47f65dc692c0474552c5f0180f2d5a7fc5730e2954d0f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
  run:
    - matplotlib-base >=2.2.4
    - numpy >=1.16.0
    - python >=3.5,<4.0

test:
  imports:
    - e13tools
    - e13tools.sampling
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://e13tools.readthedocs.io
  summary: A collection of utility functions
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 1313e
